### ISSUE TITLE
Нестандартная функция

### ISSUE THREAD

**Issue by justnik98** [tihomirovnick/home#1]
Данная функция не является частью стандарта языка Си, это какая-то магия MSVS.
https://github.com/tihomirovnick/home/blob/c8a5d5af045608bc19f57a04808fcc776f905870/main.c#L5

**Comment by tihomirovnick** [comment]
Я сначала писал scanf, но вылезала ошибка и предлагало дописать _s, после
этого все заработало

пт, 17 сент. 2021 г., 00:10 Nikita Yankovskii ***@***.***>:

**Comment by tihomirovnick** [comment]
Но я помню и знаю, что правильно писать scanf

пт, 17 сент. 2021 г., 00:10 Nikita Yankovskii ***@***.***>:
